In [2]:
import pandas as pd
df = pd.DataFrame({
    "NAME":["YUSUF","RAHUL"],
    "AGE":[22,21]
})
print(df)

    NAME  AGE
0  YUSUF   22
1  RAHUL   21

In [1]:
from PyPDF2 import PdfReader

reader = PdfReader(r"C:\Users\Dell\Desktop\practice_dataset.csv.pdf")

for page in reader.pages:
    print(page.extract_text())

ModuleNotFoundError: No module named 'PyPDF2'

In [6]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [7]:
df.head()
df.tail()
df.shape
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [8]:
df.shape

(303, 14)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [10]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [12]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [13]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [16]:
# method :describe() Statistical summary of the numerical column
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [17]:
df.isna()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
df['age']

0      63
1      37
2      41
3      56
4      57
       ..
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [19]:
df[["age","sex"]]

     age  sex
0     63    1
1     37    1
2     41    0
3     56    1
4     57    0
..   ...  ...
298   57    0
299   45    1
300   68    1
301   57    1
302   57    0

[303 rows x 2 columns]

In [20]:
df ['age'].value_counts()

age
58    19
57    17
54    16
59    14
52    13
51    12
62    11
60    11
44    11
56    11
64    10
41    10
63     9
67     9
65     8
43     8
45     8
55     8
42     8
61     8
53     8
46     7
48     7
66     7
50     7
49     5
47     5
70     4
39     4
35     4
68     4
38     3
71     3
40     3
69     3
34     2
37     2
29     1
74     1
76     1
77     1
Name: count, dtype: int64

In [22]:
#drop
df.drop("age",axis = 1)

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [11]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Dell\Downloads\dataset (2).csv")
print(df.head())

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0
1   37    1   2       130   250    0        1      187      0      3.5      0
2   41    0   1       130   204    0        0      172      0      1.4      2
3   56    1   1       120   236    0        1      178      0      0.8      2
4   57    0   0       120   354    0        1      163      1      0.6      2

   ca  thal  target
0   0     1       1
1   0     2       1
2   0     2       1
3   0     2       1
4   0     2       1

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [6]:
df['oldpeak'].notnull()

0      True
1      True
2      True
3      True
4      True
       ...
298    True
299    True
300    True
301    True
302    True
Name: oldpeak, Length: 303, dtype: bool

In [3]:
df = pd.read_csv(r"C:\Users\Dell\Downloads\customer_churn.csv")
df

NameError: name 'pd' is not defined

In [26]:
df.replaces(({'gender':{"Male":1,"Female":0}}),inplace = True)
df.head

AttributeError: 'DataFrame' object has no attribute 'replaces'

In [19]:
df.sort_values("age")

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
499,18,56381.863427,553.426728,31,79.289428,270,76,2,Male,East,0
101,18,84060.392867,654.317589,26,136.519956,204,16,3,Male,North,1
726,18,28960.920923,628.085938,38,125.983918,34,30,5,Male,North,1
850,18,46798.356936,543.748838,35,101.329648,240,72,3,Male,West,0
845,18,47838.686664,622.903021,27,57.648520,284,100,5,Male,North,1
...,...,...,...,...,...,...,...,...,...,...,...
390,69,29310.211580,628.437600,26,115.414367,277,55,2,Male,West,0
218,69,42159.154692,674.544107,34,101.854544,40,77,4,Male,West,1
469,69,55280.830948,738.334505,37,174.404636,81,26,5,Male,West,0
520,69,50894.455549,594.530606,26,143.495668,230,86,2,Male,North,1
892,69,72067.554912,728.217917,30,172.909779,30,10,4,Female,East,1

In [28]:
df.groupby( "region")['churn'].count()

region
East     225
North    257
South    267
West     251
Name: churn, dtype: int64

In [31]:
# Transform()
df["age"].transform(lambda x : "old_person" if x > 45 else"young_person")
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ravi", "Priya", "Ravi", None],
    "Age": [25, 30, 25, None],
    "Salary": [50000, 60000, 50000, 70000]
})

In [3]:
df.head(3)

    Name   Age  Salary
0   Ravi  25.0   50000
1  Priya  30.0   60000
2   Ravi  25.0   50000

df.tail(2)

In [7]:
df.tail(2)

   Name   Age  Salary
2  Ravi  25.0   50000
3  None   NaN   70000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      float64
 2   Salary  4 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes

In [9]:
df.describe()

             Age        Salary
count   3.000000      4.000000
mean   26.666667  57500.000000
std     2.886751   9574.271078
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    25.000000  55000.000000
75%    27.500000  62500.000000
max    30.000000  70000.000000

In [10]:
df.memory_usage(deep=True)

Index     132
Name      184
Age        32
Salary     32
dtype: int64

In [11]:
df2 = df.copy()

In [12]:
df2

    Name   Age  Salary
0   Ravi  25.0   50000
1  Priya  30.0   60000
2   Ravi  25.0   50000
3   None   NaN   70000

In [13]:
df.T

            0      1      2      3
Name     Ravi  Priya   Ravi   None
Age      25.0   30.0   25.0    NaN
Salary  50000  60000  50000  70000

In [14]:
df.drop(columns=['Age'])

    Name  Salary
0   Ravi   50000
1  Priya   60000
2   Ravi   50000
3   None   70000

In [15]:
df.drop(index=[0])

    Name   Age  Salary
1  Priya  30.0   60000
2   Ravi  25.0   50000
3   None   NaN   70000

In [16]:
df.drop_duplicates()

    Name   Age  Salary
0   Ravi  25.0   50000
1  Priya  30.0   60000
3   None   NaN   70000

In [17]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [18]:
df[df.duplicated()]

   Name   Age  Salary
2  Ravi  25.0   50000

In [19]:
df.rename(columns={"Name":"Full Name"})

  Full Name   Age  Salary
0      Ravi  25.0   50000
1     Priya  30.0   60000
2      Ravi  25.0   50000
3      None   NaN   70000

In [20]:
df["Age"] = df["Age"].astype(float)

In [21]:
25
30

30

In [22]:
df["Salary"] = df["Salary"].astype(str)

In [23]:
df.fillna(0)

    Name   Age Salary
0   Ravi  25.0  50000
1  Priya  30.0  60000
2   Ravi  25.0  50000
3      0   0.0  70000

In [24]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    30.000000
2    25.000000
3    26.666667
Name: Age, dtype: float64

In [25]:
df.dropna()

    Name   Age Salary
0   Ravi  25.0  50000
1  Priya  30.0  60000
2   Ravi  25.0  50000

In [26]:
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False  False   False
2  False  False   False
3   True   True   False

In [27]:
df.isnull().sum()

Name      1
Age       1
Salary    0
dtype: int64

In [28]:
df.notnull()

    Name    Age  Salary
0   True   True    True
1   True   True    True
2   True   True    True
3  False  False    True

In [29]:
df[df["Age"].notnull()]

    Name   Age Salary
0   Ravi  25.0  50000
1  Priya  30.0  60000
2   Ravi  25.0  50000

In [30]:
df.replace(0, 999)

    Name   Age Salary
0   Ravi  25.0  50000
1  Priya  30.0  60000
2   Ravi  25.0  50000
3   None   NaN  70000

In [4]:
df.sort_values("Age", ascending=False)

    Name   Age  Salary
1  Priya  30.0   60000
0   Ravi  25.0   50000
2   Ravi  25.0   50000
3   None   NaN   70000

In [10]:
df.groupby("Name")["Salary"].mean()

Name
Priya    60000.0
Ravi     50000.0
Name: Salary, dtype: float64

In [11]:
df["Avg_Salary"] = df.groupby("Name")["Salary"].transform("mean")
print(df)

    Name   Age  Salary  Avg_Salary
0   Ravi  25.0   50000     50000.0
1  Priya  30.0   60000     60000.0
2   Ravi  25.0   50000     50000.0
3   None   NaN   70000         NaN

In [13]:
df.query("Age > 25")

    Name   Age  Salary  Avg_Salary
1  Priya  30.0   60000     60000.0

In [16]:
df.where(df["Age"] > 25)

    Name   Age   Salary  Avg_Salary
0    NaN   NaN      NaN         NaN
1  Priya  30.0  60000.0     60000.0
2    NaN   NaN      NaN         NaN
3    NaN   NaN      NaN         NaN

In [18]:
df.mask(df["Age"] < 30)

    Name   Age   Salary  Avg_Salary
0    NaN   NaN      NaN         NaN
1  Priya  30.0  60000.0     60000.0
2    NaN   NaN      NaN         NaN
3   None   NaN  70000.0         NaN

#apply

In [20]:
df["Salary"].apply(lambda x:x+5000)

0    55000
1    65000
2    55000
3    75000
Name: Salary, dtype: int64

In [21]:
df["Name"].map({
    "Ravi":"Developer",
    "Priya":"Tester"
})

0    Developer
1       Tester
2    Developer
3          NaN
Name: Name, dtype: object

In [22]:
df["Name"].value_counts()

Name
Ravi     2
Priya    1
Name: count, dtype: int64

In [23]:
df["Name"].unique()

array(['Ravi', 'Priya', None], dtype=object)

In [24]:
df["Name"].nunique()

2

In [25]:
df.sample(2)

   Name   Age  Salary  Avg_Salary
3  None   NaN   70000         NaN
2  Ravi  25.0   50000     50000.0

In [26]:
df.set_index("Name")

        Age  Salary  Avg_Salary
Name
Ravi   25.0   50000     50000.0
Priya  30.0   60000     60000.0
Ravi   25.0   50000     50000.0
None    NaN   70000         NaN

In [27]:
df["Salary"].mean()

np.float64(57500.0)

In [28]:
df["Age"].median()

25.0

In [29]:
df.head()

    Name   Age  Salary  Avg_Salary
0   Ravi  25.0   50000     50000.0
1  Priya  30.0   60000     60000.0
2   Ravi  25.0   50000     50000.0
3   None   NaN   70000         NaN

In [30]:
df["Age"].median()

25.0

In [31]:
df["Salary"].min()

50000

In [32]:
df["Salary"].min()

50000

In [33]:
df["Name"].unique()

array(['Ravi', 'Priya', None], dtype=object)

In [34]:
df["Name"].nunique()

2

In [35]:
df.set_index("Name")

        Age  Salary  Avg_Salary
Name
Ravi   25.0   50000     50000.0
Priya  30.0   60000     60000.0
Ravi   25.0   50000     50000.0
None    NaN   70000         NaN

In [36]:
df["Salary"].min()

50000

In [37]:
df["Age"].count()

np.int64(3)

In [38]:
df["Salary"].std()

9574.27107756338

In [39]:
df["Salary"].rank()

0    1.5
1    3.0
2    1.5
3    4.0
Name: Salary, dtype: float64

In [40]:
df.head()

    Name   Age  Salary  Avg_Salary
0   Ravi  25.0   50000     50000.0
1  Priya  30.0   60000     60000.0
2   Ravi  25.0   50000     50000.0
3   None   NaN   70000         NaN

In [41]:
df.nlargest(2,"Salary")

    Name   Age  Salary  Avg_Salary
3   None   NaN   70000         NaN
1  Priya  30.0   60000     60000.0

In [2]:
df = Pd.read_csv(r"C:\Users\Dell\Downloads\customer_churn.csv")
df

NameError: name 'Pd' is not defined

In [4]:
df.head()

NameError: name 'df' is not defined

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\Downloads\customer_churn.csv")
df.head()

,age,income,credit_score,transactions_month,avg_purchase_value,days_since_last_login,tenure_months,num_products,gender,region,churn
0,56,NaN,770.887470,29,84.828689,143,90,1,Male,South,1
1,69,53051.954538,622.025467,41,133.943805,72,96,4,Female,East,1
2,46,38654.738821,665.727931,36,114.993023,155,88,3,Male,North,1
3,32,28666.194356,715.281358,29,153.875284,76,110,2,Male,South,0
4,60,40301.406736,NaN,27,115.391031,168,99,2,Male,East,1

In [3]:
#select_dtypes()
numerical_col = df.select_dtypes(include ="number")

In [4]:
intger_col = df.select_dtypes(include = "int64")
float_col = df.select_dtypes(include = "float64")
cat_col = df.select_dtypes(include = "object")

In [5]:
df['age'].dtypes

dtype('int64')

In [6]:
df.columns

Index(['age', 'income', 'credit_score', 'transactions_month',
       'avg_purchase_value', 'days_since_last_login', 'tenure_months',
       'num_products', 'gender', 'region', 'churn'],
      dtype='object')

In [7]:
import pandas as pd

df = pd.DataFrame({
    'date': [
        '2024-01-15',      # YYYY-MM-DD
        '15/01/2024',      # DD/MM/YYYY
        '01-15-2024',      # MM-DD-YYYY
        'Jan 15 2024',     # Month name
        '15 January 2024', # Full month name
        20240115           # Compact format
    ]
})

print(df)

              date
0       2024-01-15
1       15/01/2024
2       01-15-2024
3      Jan 15 2024
4  15 January 2024
5         20240115

In [8]:
df['date'] = pd.to_datetime(df['date'], format='mixed')

print(df)
print(df.dtypes)

                           date
0 2024-01-15 00:00:00.000000000
1 2024-01-15 00:00:00.000000000
2 2024-01-15 00:00:00.000000000
3 2024-01-15 00:00:00.000000000
4 2024-01-15 00:00:00.000000000
5 1970-01-01 00:00:00.020240115
date    datetime64[ns]
dtype: object

In [14]:
import pandas as pd

df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.strftime("%m-%d-%Y")

df

         date
0  01-15-2024
1  01-15-2024
2  01-15-2024
3  01-15-2024
4  01-15-2024
5  01-01-1970

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    6 non-null      object
dtypes: object(1)
memory usage: 180.0+ bytes

In [19]:
df['date'].dtype

dtype('O')

In [20]:
import pandas as pd

df['date'] = pd.to_datetime(df['date'])

In [21]:
df['month'] = df['date'].dt.month

In [22]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2024-01-15', '2024-02-20', '2024-03-25']
})

# String → Datetime
df['date'] = pd.to_datetime(df['date'])

# Extract month
df['month'] = df['date'].dt.month

print(df)

        date  month
0 2024-01-15      1
1 2024-02-20      2
2 2024-03-25      3

In [30]:
df = pd.DataFrame({"price":["$10,000","$20,000","$30,000","$40,000"]})

In [31]:
df

     price
0  $10,000
1  $20,000
2  $30,000
3  $40,000

In [32]:
df["price"] = df["price"].str.replace(" ", "", regex=False)

df

     price
0  $10,000
1  $20,000
2  $30,000
3  $40,000

In [33]:
df.dtypes

price    object
dtype: object

In [36]:
import pandas as pd

df = pd.DataFrame({
    "price": [10.5, 20.75, 30.25]
})

df["price"] = df["price"].astype("int64")

print(df)

   price
0     10
1     20
2     30

In [37]:
df.dtypes

price    int64
dtype: object

In [38]:
import pandas as pd
from sklearn.impute import KNNImputer

df = pd.DataFrame({
    "Age": [25, 26, 27, 28, 29],
    "Salary": [30000, 32000, None, 34000, 36000]
})

imputer = KNNImputer(n_neighbors=2)

df[:] = imputer.fit_transform(df)

print(df)

   Age   Salary
0   25  30000.0
1   26  32000.0
2   27  33000.0
3   28  34000.0
4   29  36000.0

In [39]:
KNNImputer(n_neighbors=3)

KNNImputer(n_neighbors=3)

In [40]:
#Handle the Outlier
df = pd.DataFrame({"age":[32,43,23,45,54,23,45,129,31,180,10,2]})

In [3]:
df

NameError: name 'df' is not defined

In [1]:
import camelot

tables = camelot.read_pdf(
    r"C:\Users\Dell\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\7D421948E18EF6651CBACDF0C02FB186303B6D25\transfers\2026-26\Pandas_Practice_Dataset.xlsx.pdf",
    pages="all"
)

tables[0].df.to_csv("output.csv", index=False)

ModuleNotFoundError: No module named 'camelot'

In [2]:
!pip install camelot-py

Collecting camelot-py
  Downloading camelot_py-2.0.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: click>=8.0.1 in c:\users\dell\anaconda3\lib\site-packages (from camelot-py) (8.2.1)
Requirement already satisfied: numpy>=1.26.1 in c:\users\dell\anaconda3\lib\site-packages (from camelot-py) (2.3.5)
Requirement already satisfied: openpyxl>=3.1.0 in c:\users\dell\anaconda3\lib\site-packages (from camelot-py) (3.1.5)
Requirement already satisfied: pandas>=2.2.2 in c:\users\dell\anaconda3\lib\site-packages (from camelot-py) (2.3.3)
Requirement already satisfied: tabulate>=0.9.0 in c:\users\dell\anaconda3\lib\site-packages (from camelot-py) (0.9.0)
Collecting opencv-python-headless>=4.7.0.68 (from camelot-py)
  Downloading opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting pypdfium2>=4 (from camelot-py)
  Downloading pypdfium2-5.10.1-py3-none-win_amd64.whl.metadata (70 kB)
Requirement already satisfied: pillow>=10.4.0 in c:\users\dell\anaconda3\lib\site-packages (from camelot-py) (12.0.0)
Collecting playa-pdf>=0.8.1 (from camelot-py)
  Downloading playa_pdf-1.1.0-cp313-cp313-win_amd64.whl.metadata (27 kB)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\lib\site-packages (from click>=8.0.1->camelot-py) (0.4.6)
Requirement already satisfied: et-xmlfile in c:\users\dell\anaconda3\lib\site-packages (from openpyxl>=3.1.0->camelot-py) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=2.2.2->camelot-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=2.2.2->camelot-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas>=2.2.2->camelot-py) (2025.2)
Requirement already satisfied: mypy-extensions in c:\users\dell\anaconda3\lib\site-packages (from playa-pdf>=0.8.1->camelot-py) (1.0.0)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.2->camelot-py) (1.17.0)
Downloading camelot_py-2.0.0-py3-none-any.whl (113 kB)
Downloading opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl (40.1 MB)
   ---------------------------------------- 0.0/40.1 MB ? eta -:--:--
    --------------------------------------- 0.5/40.1 MB 3.8 MB/s eta 0:00:11
   - -------------------------------------- 1.8/40.1 MB 4.4 MB/s eta 0:00:09
   --- ------------------------------------ 3.1/40.1 MB 4.9 MB/s eta 0:00:08
   ---- ----------------------------------- 4.5/40.1 MB 5.2 MB/s eta 0:00:07
   ----- ---------------------------------- 5.5/40.1 MB 5.2 MB/s eta 0:00:07
   ------- -------------------------------- 7.1/40.1 MB 5.5 MB/s eta 0:00:07
   -------- ------------------------------- 8.1/40.1 MB 5.4 MB/s eta 0:00:06
   --------- ------------------------------ 9.4/40.1 MB 5.5 MB/s eta 0:00:06
   ---------- ----------------------------- 10.7/40.1 MB 5.7 MB/s eta 0:00:06
   ------------ --------------------------- 12.3/40.1 MB 5.8 MB/s eta 0:00:05
   ------------- -------------------------- 13.6/40.1 MB 5.9 MB/s eta 0:00:05
   -------------- ------------------------- 14.7/40.1 MB 5.8 MB/s eta 0:00:05
   --------------- ------------------------ 16.0/40.1 MB 5.8 MB/s eta 0:00:05
   ----------------- ---------------------- 17.3/40.1 MB 5.9 MB/s eta 0:00:04
   ------------------ --------------------- 18.9/40.1 MB 5.9 MB/s eta 0:00:04
   -------------------- ------------------- 20.2/40.1 MB 6.0 MB/s eta 0:00:04
   --------------------- ------------------ 21.2/40.1 MB 6.0 MB/s eta 0:00:04
   ---------------------- ----------------- 22.8/40.1 MB 6.0 MB/s eta 0:00:03
   ------------------------ --------------- 24.1/40.1 MB 6.0 MB/s eta 0:00:03
   ------------------------- -------------- 25.4/40.1 MB 6.0 MB/s eta 0:00:03
   -------------------------- ------------- 26.7/40.1 MB 6.0 MB/s eta 0:00:03
   ---------------------------- ----------- 28.0/40.1 MB 6.0 MB/s eta 0:00:03
   ----------------------------- ---------- 29.4/40.1 MB 6.0 MB/s eta 0:00:02
   ------------------------------ --------- 30.7/40.1 MB 6.0 MB/s eta 0:00:02
   ------------------------------- -------- 32.0/40.1 MB 6.0 MB/s eta 0:00:02
   --------------------------------- ------ 33.3/40.1 MB 6.0 MB/s eta 0:00:02
   ---------------------------------- ----- 34.6/40.1 MB 6.0 MB/s eta 0:00:01
   ----------------------------------- ---- 35.9/40.1 MB 6.0 MB/s eta 0:00:01
   ------------------------------------- -- 37.2/40.1 MB 6.0 MB/s eta 0:00:01
   ------------------------------------- -- 38.0/40.1 MB 5.9 MB/s eta 0:00:01
   -------------------------------------- - 39.1/40.1 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------  39.8/40.1 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 40.1/40.1 MB 5.8 MB/s  0:00:06
Downloading playa_pdf-1.1.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.2 MB 2.7 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.2 MB 2.8 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.2 MB 2.9 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.2 MB 3.1 MB/s eta 0:00:02
   ----------------- ---------------------- 3.7/8.2 MB 3.1 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.2 MB 3.2 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.2 MB 3.3 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 3.3 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 7.6/8.2 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 3.3 MB/s  0:00:02
Downloading pypdfium2-5.10.1-py3-none-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -------- ------------------------------- 0.8/3.8 MB 3.3 MB/s eta 0:00:01
   ---------------- ----------------------- 1.6/3.8 MB 3.6 MB/s eta 0:00:01
   ------------------------ --------------- 2.4/3.8 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 3.9 MB/s  0:00:00
Installing collected packages: pypdfium2, playa-pdf, opencv-python-headless, camelot-py

   ---------------------------------------- 0/4 [pypdfium2]
   ---------------------------------------- 0/4 [pypdfium2]
   ---------------------------------------- 0/4 [pypdfium2]
   ---------- ----------------------------- 1/4 [playa-pdf]
   ---------- ----------------------------- 1/4 [playa-pdf]
   ---------- ----------------------------- 1/4 [playa-pdf]
   ---------- ----------------------------- 1/4 [playa-pdf]
   ---------- ----------------------------- 1/4 [playa-pdf]
   ---------- ----------------------------- 1/4 [playa-pdf]
   ---------- ----------------------------- 1/4 [playa-pdf]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   -------------------- ------------------- 2/4 [opencv-python-headless]
   ------------------------------ --------- 3/4 [camelot-py]
   ------------------------------ --------- 3/4 [camelot-py]
   ---------------------------------------- 4/4 [camelot-py]

Successfully installed camelot-py-2.0.0 opencv-python-headless-4.13.0.92 playa-pdf-1.1.0 pypdfium2-5.10.1

In [4]:
!pip show camelot-py

Name: camelot-py
Version: 2.0.0
Summary: PDF Table Extraction for Humans.
Home-page: https://github.com/camelot-dev/camelot
Author:
Author-email: Vinayak Mehta <vmehta94@gmail.com>
License: MIT
Location: C:\Users\Dell\anaconda3\Lib\site-packages
Requires: click, numpy, opencv-python-headless, openpyxl, pandas, pillow, playa-pdf, pypdfium2, tabulate
Required-by:

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\Downloads\Pandas_Practice_Dataset.xlsx (1).csv")
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43,Female,Chennai,48886,26.0,NaN,02/09/2022,90.81,N,4.5
1,2,Kiran,35,F,Bengaluru,"₹75,196",14.0,NaN,04/01/2023,70.98,NaN,3.5
2,3,Neha,44,M,NaN,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38,F,HYD,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,F,hyd,64961,17.0,hr,28/03/2018,98.68,Yes,12.0

In [9]:
df.isnull()

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,True,False
2,False,False,False,False,True,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,True,False,False,False,False,False,True,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
df.isnull()

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,True,False
2,False,False,False,False,True,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,True,False,False,False,False,False,True,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df.dropna()

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
3,79,Sneha,38,F,HYD,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,F,hyd,64961,17.0,hr,28/03/2018,98.68,Yes,12.0
5,6,Pooja,28,F,Delhi,38199,27.0,hr,19-Mar-2020,96.75,no,1.9
10,11,Neha,56,M,hyd,81538,13.0,it,2021-04-19,42.72,yes,1.9
12,13,Amit,29,Female,Mumbai,33324,14.0,hr,02-06-2021,89.12,yes,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...
994,995,Ravi,50,Unknown,Hyderabad,113924,18.0,it,25/01/2021,82.53,Yes,2.3
995,996,Kiran,57,Male,Hyderabad,105886,12.0,IT,2019-08-15,40.16,no,4.3
997,998,Ravi,22,Unknown,Bangalore,85273,0.0,Sales,04-Mar-2023,50.90,Yes,1.6
998,999,Rohit,21,F,Mumbai,78945,13.0,hr,2021-11-16,61.89,No,3.8
999,1000,Rahul,52,Male,Chennai,66489,26.0,hr,05-Oct-2021,98.59,no,1.8

In [12]:
df.dropna(axis=1)

     Customer_ID Joining_Date
0              1   02/09/2022
1              2   04/01/2023
2              3  23-Jun-2023
3             79   2021-01-04
4              5   28/03/2018
..           ...          ...
995          996   2019-08-15
996           22   11-23-2022
997          998  04-Mar-2023
998          999   2021-11-16
999         1000  05-Oct-2021

[1000 rows x 2 columns]

In [14]:
df["Age"].dtype

dtype('O')

In [15]:
print(df["Age"].unique())

['43' '35' '44' '38' '46' '28' '59' '22' '-5' '58' '56' '52' '29' '42'
 '20' '36' '54' '39' '45' '25' '53' '34' '27' '49' '23' '30' '32' '37'
 '50' '57' '33' '41' '24' '51' '26' '21' '48' '55' '47' '60' '180' '31'
 '40' '150' 'twenty' nan]

In [16]:
df["Age"] = df["Age"].replace({
    "Twenty Five": 25,
    "45 years": 45,
    "Unknown": None
})

In [17]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [18]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [19]:
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43.0,Female,Chennai,48886,26.0,NaN,02/09/2022,90.81,N,4.5
1,2,Kiran,35.0,F,Bengaluru,"₹75,196",14.0,NaN,04/01/2023,70.98,NaN,3.5
2,3,Neha,44.0,M,NaN,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38.0,F,HYD,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46.0,F,hyd,64961,17.0,hr,28/03/2018,98.68,Yes,12.0

In [20]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [21]:
df["Age"]=df["Age"].ffill()

In [22]:
| Age |
| --- |
| 20  |
| NaN |
| 35  |

SyntaxError: invalid syntax (3624600508.py, line 1)

In [23]:
df["Name"]=df["Name"].fillna("Unknown")

In [ ]:
from sklearn.impute import KNNImputer

imputer=KNNImputer(n_neighbors=2)

df[["Age"]]=imputer.fit_transform(df[["Age"]])

In [3]:
df.head()

,Customer_ID,Name,Age,Gender,City,Salary,Experience,Department,Joining_Date,Performance_Score,Loan_Status,Rating
0,1,Amit,43,Female,Chennai,48886,26.0,NaN,02/09/2022,90.81,N,4.5
1,2,Kiran,35,F,Bengaluru,"₹75,196",14.0,NaN,04/01/2023,70.98,NaN,3.5
2,3,Neha,44,M,NaN,111831,28.0,IT,23-Jun-2023,65.04,NaN,-2.0
3,79,Sneha,38,F,HYD,72973,3.0,HR,2021-01-04,65.51,no,1.4
4,5,Rohit,46,F,hyd,64961,17.0,hr,28/03/2018,98.68,Yes,12.0

# Employee_dataset

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Dell\Downloads\HR_Employee_Dataset.csv")

df

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating
0,EMP2000,Employee_0,42,Male,Marketing,Executive,144857,13.4,2019-06-11,1
1,EMP2001,Employee_1,42,Female,IT,Manager,39738,17.5,2015-10-14,5
2,EMP2002,Employee_2,26,Female,Operations,Executive,30703,15.3,2022-09-05,2
3,EMP2003,Employee_3,41,Male,Operations,Executive,133776,14.7,2018-05-20,5
4,EMP2004,Employee_4,58,Female,HR,Executive,69422,9.9,2019-03-28,5
...,...,...,...,...,...,...,...,...,...,...
495,EMP2495,Employee_495,43,Female,Finance,Manager,143805,9.7,2023-02-06,1
496,EMP2496,Employee_496,54,Female,Marketing,Executive,113846,1.3,2019-10-03,4
497,EMP2497,Employee_497,57,Female,Finance,Executive,42927,14.1,2022-08-21,1
498,EMP2498,Employee_498,44,Male,Marketing,Associate,140589,6.9,2020-05-25,4
499,EMP2499,Employee_499,55,Male,Marketing,Executive,135657,15.0,2020-12-12,1

# Easy level

In [4]:
# method 1 employees in each department 
df["Department"].value_counts()

Department
IT            121
Finance       109
Operations     94
HR             94
Marketing      82
Name: count, dtype: int64

In [5]:
df["Gender"].value_counts(normalize=True)*100

Gender
Female    50.6
Male      49.4
Name: proportion, dtype: float64

In [6]:
df["Salary"].mean()

np.float64(83582.674)

In [7]:
df[df["Age"]>50]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating
4,EMP2004,Employee_4,58,Female,HR,Executive,69422,9.9,2019-03-28,5
6,EMP2006,Employee_6,54,Male,Operations,Analyst,81899,11.3,2020-01-11,4
10,EMP2010,Employee_10,56,Female,IT,Manager,35641,18.3,2017-02-16,1
12,EMP2012,Employee_12,55,Female,Marketing,Analyst,26305,14.8,2021-09-20,1
14,EMP2014,Employee_14,53,Female,Operations,Analyst,38782,8.5,2019-02-22,1
...,...,...,...,...,...,...,...,...,...,...
488,EMP2488,Employee_488,52,Female,Operations,Manager,72003,13.3,2020-09-19,1
493,EMP2493,Employee_493,59,Male,Finance,Manager,114283,16.6,2018-08-11,1
496,EMP2496,Employee_496,54,Female,Marketing,Executive,113846,1.3,2019-10-03,4
497,EMP2497,Employee_497,57,Female,Finance,Executive,42927,14.1,2022-08-21,1
499,EMP2499,Employee_499,55,Male,Marketing,Executive,135657,15.0,2020-12-12,1

In [8]:
df[df["Performance_Rating"]==5]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating
1,EMP2001,Employee_1,42,Female,IT,Manager,39738,17.5,2015-10-14,5
3,EMP2003,Employee_3,41,Male,Operations,Executive,133776,14.7,2018-05-20,5
4,EMP2004,Employee_4,58,Female,HR,Executive,69422,9.9,2019-03-28,5
7,EMP2007,Employee_7,30,Female,IT,Analyst,32392,4.7,2019-08-24,5
8,EMP2008,Employee_8,30,Female,Finance,Lead,64724,4.6,2015-07-30,5
...,...,...,...,...,...,...,...,...,...,...
477,EMP2477,Employee_477,49,Female,Marketing,Manager,85552,9.0,2023-03-09,5
485,EMP2485,Employee_485,58,Female,Operations,Lead,58724,18.8,2016-03-31,5
487,EMP2487,Employee_487,57,Male,Marketing,Analyst,123119,5.3,2016-05-21,5
489,EMP2489,Employee_489,23,Male,Finance,Executive,88379,4.4,2021-04-05,5
492,EMP2492,Employee_492,30,Female,Finance,Analyst,117454,1.8,2021-03-05,5

In [9]:
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"])

df[df["Joining_Date"].dt.year>2020]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating
2,EMP2002,Employee_2,26,Female,Operations,Executive,30703,15.3,2022-09-05,2
12,EMP2012,Employee_12,55,Female,Marketing,Analyst,26305,14.8,2021-09-20,1
21,EMP2021,Employee_21,40,Male,IT,Analyst,144591,5.3,2023-01-08,5
26,EMP2026,Employee_26,59,Female,IT,Associate,138360,2.9,2023-02-03,3
28,EMP2028,Employee_28,50,Male,Marketing,Lead,24765,13.1,2021-05-13,3
...,...,...,...,...,...,...,...,...,...,...
489,EMP2489,Employee_489,23,Male,Finance,Executive,88379,4.4,2021-04-05,5
491,EMP2491,Employee_491,30,Male,Operations,Manager,111996,4.9,2021-12-11,1
492,EMP2492,Employee_492,30,Female,Finance,Analyst,117454,1.8,2021-03-05,5
495,EMP2495,Employee_495,43,Female,Finance,Manager,143805,9.7,2023-02-06,1
497,EMP2497,Employee_497,57,Female,Finance,Executive,42927,14.1,2022-08-21,1

In [10]:
(df["Joining_Date"].dt.year>2020).sum()

np.int64(134)

In [11]:
print(df["Age"].min())
print(df["Age"].max())

22
59

In [12]:
df.nlargest(10,"Salary")

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating
192,EMP2192,Employee_192,22,Female,IT,Manager,149593,7.6,2019-01-17,5
91,EMP2091,Employee_91,29,Female,Finance,Executive,149572,13.2,2020-03-30,5
213,EMP2213,Employee_213,25,Female,Operations,Executive,149036,6.3,2022-01-11,1
468,EMP2468,Employee_468,30,Male,Finance,Lead,148886,12.6,2021-06-10,3
165,EMP2165,Employee_165,57,Male,HR,Analyst,148652,17.9,2016-03-29,3
423,EMP2423,Employee_423,43,Female,Operations,Manager,148447,8.6,2020-03-06,5
444,EMP2444,Employee_444,40,Male,Operations,Executive,147928,13.1,2018-06-07,1
402,EMP2402,Employee_402,43,Female,Finance,Associate,147581,12.0,2018-10-18,2
75,EMP2075,Employee_75,42,Male,HR,Executive,146503,2.3,2020-05-23,4
240,EMP2240,Employee_240,55,Female,Marketing,Manager,146278,18.9,2020-02-26,2

In [13]:
df["Designation"].value_counts()

Designation
Executive    108
Associate    103
Lead         102
Manager       97
Analyst       90
Name: count, dtype: int64

In [14]:
df[df["Department"]=="IT"]["Experience_Years"].mean()

np.float64(9.879338842975207)

# medium level

In [15]:
#1. Department wise average salary

df.groupby("Department")["Salary"].mean()

Department
Finance       82828.073394
HR            85806.319149
IT            78075.330579
Marketing     86696.658537
Operations    86606.829787
Name: Salary, dtype: float64

In [16]:
#2. Highest average performance department
df.groupby("Department")["Performance_Rating"].mean().sort_values(ascending=False)

Department
IT            3.016529
Marketing     2.914634
Finance       2.899083
HR            2.787234
Operations    2.744681
Name: Performance_Rating, dtype: float64

In [17]:
#3. Salary above company average
avg=df["Salary"].mean()

df[df["Salary"]>avg]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating
0,EMP2000,Employee_0,42,Male,Marketing,Executive,144857,13.4,2019-06-11,1
3,EMP2003,Employee_3,41,Male,Operations,Executive,133776,14.7,2018-05-20,5
5,EMP2005,Employee_5,24,Female,HR,Manager,103106,14.0,2018-01-14,1
11,EMP2011,Employee_11,38,Male,Finance,Associate,99534,11.2,2016-05-17,4
13,EMP2013,Employee_13,45,Female,Operations,Lead,118262,7.3,2020-04-28,2
...,...,...,...,...,...,...,...,...,...,...
493,EMP2493,Employee_493,59,Male,Finance,Manager,114283,16.6,2018-08-11,1
495,EMP2495,Employee_495,43,Female,Finance,Manager,143805,9.7,2023-02-06,1
496,EMP2496,Employee_496,54,Female,Marketing,Executive,113846,1.3,2019-10-03,4
498,EMP2498,Employee_498,44,Male,Marketing,Associate,140589,6.9,2020-05-25,4
499,EMP2499,Employee_499,55,Male,Marketing,Executive,135657,15.0,2020-12-12,1

In [18]:
#4. Age Group
def age_group(age):
    if age<=30:
        return "Young"
    elif age<=45:
        return "Mid"
    else:
        return "Senior"

df["Age_Group"]=df["Age"].apply(age_group)

df["Age_Group"].value_counts()

Age_Group
Mid       206
Senior    184
Young     110
Name: count, dtype: int64

In [19]:
#5. Experience greater than department average
dept_avg=df.groupby("Department")["Experience_Years"].transform("mean")

df[df["Experience_Years"]>dept_avg]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group
0,EMP2000,Employee_0,42,Male,Marketing,Executive,144857,13.4,2019-06-11,1,Mid
1,EMP2001,Employee_1,42,Female,IT,Manager,39738,17.5,2015-10-14,5,Mid
2,EMP2002,Employee_2,26,Female,Operations,Executive,30703,15.3,2022-09-05,2,Young
3,EMP2003,Employee_3,41,Male,Operations,Executive,133776,14.7,2018-05-20,5,Mid
5,EMP2005,Employee_5,24,Female,HR,Manager,103106,14.0,2018-01-14,1,Young
...,...,...,...,...,...,...,...,...,...,...,...
485,EMP2485,Employee_485,58,Female,Operations,Lead,58724,18.8,2016-03-31,5,Senior
488,EMP2488,Employee_488,52,Female,Operations,Manager,72003,13.3,2020-09-19,1,Senior
493,EMP2493,Employee_493,59,Male,Finance,Manager,114283,16.6,2018-08-11,1,Senior
497,EMP2497,Employee_497,57,Female,Finance,Executive,42927,14.1,2022-08-21,1,Senior
499,EMP2499,Employee_499,55,Male,Marketing,Executive,135657,15.0,2020-12-12,1,Senior

In [21]:
#6. Salary Growth Ratio
df["Salary_Ratio"]=df["Salary"]/df["Experience_Years"]

df.nlargest(10,"Salary_Ratio")

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group,Salary_Ratio
329,EMP2329,Employee_329,57,Male,Operations,Analyst,136452,0.7,2017-08-09,2,Senior,194931.428571
375,EMP2375,Employee_375,44,Male,IT,Executive,117512,0.7,2017-02-21,5,Mid,167874.285714
387,EMP2387,Employee_387,43,Male,HR,Associate,97853,0.6,2019-02-10,4,Mid,163088.333333
454,EMP2454,Employee_454,46,Female,IT,Executive,116131,0.8,2023-01-18,2,Senior,145163.750000
57,EMP2057,Employee_57,22,Female,IT,Manager,144997,1.0,2021-08-24,2,Young,144997.000000
103,EMP2103,Employee_103,54,Male,Operations,Associate,143239,1.0,2018-02-23,5,Senior,143239.000000
86,EMP2086,Employee_86,33,Female,IT,Lead,120356,0.9,2022-02-18,5,Mid,133728.888889
82,EMP2082,Employee_82,40,Male,IT,Associate,75798,0.6,2022-10-10,3,Mid,126330.000000
336,EMP2336,Employee_336,29,Female,Operations,Executive,98270,0.8,2018-08-03,3,Young,122837.500000
118,EMP2118,Employee_118,34,Male,Marketing,Analyst,115676,1.0,2020-12-16,5,Mid,115676.000000

In [22]:
#7. Highest average salary designation
df.groupby("Designation")["Salary"].mean().sort_values(ascending=False)

Designation
Manager      86990.381443
Executive    86486.759259
Analyst      85535.033333
Associate    81495.097087
Lead         77652.470588
Name: Salary, dtype: float64

In [23]:
#8. Departments salary >80000
dept=df.groupby("Department")["Salary"].mean()

dept[dept>80000]

Department
Finance       82828.073394
HR            85806.319149
Marketing     86696.658537
Operations    86606.829787
Name: Salary, dtype: float64

In [24]:
#9. Total salary cost department wise
df.groupby("Department")["Salary"].sum()

Department
Finance       9028260
HR            8065794
IT            9447115
Marketing     7109126
Operations    8141042
Name: Salary, dtype: int64

In [25]:
#10. Same joining year different department
df["Year"]=pd.to_datetime(df["Joining_Date"]).dt.year

df.sort_values("Year")

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group,Salary_Ratio,Year
249,EMP2249,Employee_249,58,Female,Finance,Executive,67929,18.6,2015-09-26,3,Senior,3652.096774,2015
125,EMP2125,Employee_125,41,Female,Finance,Executive,61574,3.4,2015-01-02,4,Mid,18110.000000,2015
116,EMP2116,Employee_116,23,Male,Operations,Associate,26078,12.0,2015-08-18,4,Young,2173.166667,2015
115,EMP2115,Employee_115,31,Female,Finance,Executive,116199,16.2,2015-09-06,2,Mid,7172.777778,2015
392,EMP2392,Employee_392,31,Male,Finance,Executive,109335,4.4,2015-04-11,1,Mid,24848.863636,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,EMP2218,Employee_218,38,Female,Marketing,Lead,27566,19.5,2023-02-07,3,Mid,1413.641026,2023
26,EMP2026,Employee_26,59,Female,IT,Associate,138360,2.9,2023-02-03,3,Senior,47710.344828,2023
111,EMP2111,Employee_111,33,Male,IT,Manager,24006,10.1,2023-03-06,2,Mid,2376.831683,2023
269,EMP2269,Employee_269,27,Male,IT,Lead,136972,19.7,2023-02-16,5,Young,6952.893401,2023
29,EMP2029,Employee_29,25,Female,IT,Analyst,40354,17.6,2023-03-17,2,Young,2292.840909,2023

# HARD LEVEL

In [26]:
#1. Salary > department average & Performance < department average
salary_avg=df.groupby("Department")["Salary"].transform("mean")

rating_avg=df.groupby("Department")["Performance_Rating"].transform("mean")

df[(df["Salary"]>salary_avg) &
   (df["Performance_Rating"]<rating_avg)]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group,Salary_Ratio,Year
0,EMP2000,Employee_0,42,Male,Marketing,Executive,144857,13.4,2019-06-11,1,Mid,10810.223881,2019
5,EMP2005,Employee_5,24,Female,HR,Manager,103106,14.0,2018-01-14,1,Young,7364.714286,2018
13,EMP2013,Employee_13,45,Female,Operations,Lead,118262,7.3,2020-04-28,2,Mid,16200.273973,2020
15,EMP2015,Employee_15,22,Female,IT,Manager,98257,2.9,2019-08-14,2,Young,33881.724138,2019
16,EMP2016,Employee_16,29,Male,Finance,Manager,125299,3.8,2017-01-03,2,Young,32973.421053,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,EMP2490,Employee_490,37,Female,HR,Manager,114837,6.6,2017-07-28,1,Mid,17399.545455,2017
491,EMP2491,Employee_491,30,Male,Operations,Manager,111996,4.9,2021-12-11,1,Young,22856.326531,2021
493,EMP2493,Employee_493,59,Male,Finance,Manager,114283,16.6,2018-08-11,1,Senior,6884.518072,2018
495,EMP2495,Employee_495,43,Female,Finance,Manager,143805,9.7,2023-02-06,1,Mid,14825.257732,2023
499,EMP2499,Employee_499,55,Male,Marketing,Executive,135657,15.0,2020-12-12,1,Senior,9043.800000,2020

In [27]:
#2. Salary Outliers (IQR)
def outliers(group):

    q1=group["Salary"].quantile(0.25)

    q3=group["Salary"].quantile(0.75)

    iqr=q3-q1

    lower=q1-1.5*iqr

    upper=q3+1.5*iqr

    return group[(group["Salary"]<lower) |
                 (group["Salary"]>upper)]

df.groupby("Department",group_keys=False).apply(outliers)

C:\Users\Dell\AppData\Local\Temp\ipykernel_10232\2144674372.py:17: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("Department",group_keys=False).apply(outliers)

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, Department, Designation, Salary, Experience_Years, Joining_Date, Performance_Rating, Age_Group, Salary_Ratio, Year]
Index: []

In [28]:
#3. Promotion Risk
median=df.groupby("Department")["Salary"].transform("median")

df[(df["Experience_Years"]>8)&
   (df["Performance_Rating"]>=4)&
   (df["Salary"]<median)]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group,Salary_Ratio,Year
1,EMP2001,Employee_1,42,Female,IT,Manager,39738,17.5,2015-10-14,5,Mid,2270.742857,2015
4,EMP2004,Employee_4,58,Female,HR,Executive,69422,9.9,2019-03-28,5,Senior,7012.323232,2019
6,EMP2006,Employee_6,54,Male,Operations,Analyst,81899,11.3,2020-01-11,4,Senior,7247.699115,2020
20,EMP2020,Employee_20,36,Male,HR,Lead,40566,16.2,2017-07-29,5,Mid,2504.074074,2017
56,EMP2056,Employee_56,40,Male,Finance,Analyst,36260,13.1,2018-05-15,4,Mid,2767.938931,2018
69,EMP2069,Employee_69,42,Female,Finance,Analyst,33026,15.7,2022-01-24,4,Mid,2103.566879,2022
71,EMP2071,Employee_71,45,Female,Marketing,Lead,65927,12.2,2016-03-21,4,Mid,5403.852459,2016
80,EMP2080,Employee_80,34,Male,Finance,Lead,53776,18.9,2016-06-28,4,Mid,2845.291005,2016
87,EMP2087,Employee_87,54,Male,Operations,Analyst,75161,9.5,2020-05-25,4,Senior,7911.684211,2020
96,EMP2096,Employee_96,44,Female,IT,Executive,40316,14.2,2022-01-22,5,Mid,2839.154930,2022
104,EMP2104,Employee_104,57,Female,Finance,Executive,34011,12.6,2015-12-23,5,Senior,2699.285714,2015
107,EMP2107,Employee_107,40,Male,Finance,Executive,25898,9.9,2015-01-04,4,Mid,2615.959596,2015
108,EMP2108,Employee_108,49,Female,HR,Associate,38395,15.7,2015-06-03,5,Senior,2445.541401,2015
109,EMP2109,Employee_109,41,Male,Marketing,Executive,59019,13.6,2016-07-15,4,Mid,4339.632353,2016
112,EMP2112,Employee_112,36,Male,IT,Executive,54393,12.9,2017-12-24,4,Mid,4216.511628,2017
114,EMP2114,Employee_114,50,Female,Operations,Executive,70042,8.3,2018-01-16,4,Senior,8438.795181,2018
116,EMP2116,Employee_116,23,Male,Operations,Associate,26078,12.0,2015-08-18,4,Young,2173.166667,2015
127,EMP2127,Employee_127,48,Female,HR,Associate,51417,19.8,2022-04-19,5,Senior,2596.818182,2022
158,EMP2158,Employee_158,24,Male,IT,Executive,67111,17.9,2022-06-22,4,Young,3749.217877,2022
164,EMP2164,Employee_164,53,Male,Finance,Lead,79993,16.4,2017-08-18,5,Senior,4877.621951,2017
206,EMP2206,Employee_206,51,Female,Finance,Associate,49425,10.1,2015-07-21,5,Senior,4893.564356,2015
210,EMP2210,Employee_210,56,Female,Marketing,Manager,25368,11.2,2022-06-20,5,Senior,2265.000000,2022
215,EMP2215,Employee_215,30,Female,IT,Associate,34719,15.5,2019-10-15,5,Young,2239.935484,2019
219,EMP2219,Employee_219,53,Male,IT,Lead,32306,9.7,2020-05-18,4,Senior,3330.515464,2020
223,EMP2223,Employee_223,58,Female,IT,Executive,37387,18.7,2022-07-25,4,Senior,1999.304813,2022
224,EMP2224,Employee_224,34,Female,HR,Associate,47042,10.7,2015-06-27,4,Mid,4396.448598,2015
235,EMP2235,Employee_235,22,Male,Marketing,Lead,38279,18.2,2019-09-02,5,Young,2103.241758,2019
236,EMP2236,Employee_236,49,Female,Finance,Associate,66999,19.9,2021-09-24,4,Senior,3366.783920,2021
238,EMP2238,Employee_238,56,Male,IT,Analyst,42908,15.5,2020-03-01,5,Senior,2768.258065,2020
243,EMP2243,Employee_243,38,Female,IT,Executive,57952,18.5,2020-11-11,5,Mid,3132.540541,2020
254,EMP2254,Employee_254,38,Female,Marketing,Associate,49134,15.9,2020-11-21,5,Mid,3090.188679,2020
256,EMP2256,Employee_256,57,Male,IT,Executive,67101,11.8,2017-04-03,5,Senior,5686.525424,2017
274,EMP2274,Employee_274,27,Male,Finance,Manager,48807,8.2,2015-12-21,5,Young,5952.073171,2015
307,EMP2307,Employee_307,43,Male,Marketing,Lead,75468,12.5,2015-06-28,4,Mid,6037.440000,2015
346,EMP2346,Employee_346,35,Male,Finance,Analyst,63856,15.2,2018-01-27,4,Mid,4201.052632,2018
353,EMP2353,Employee_353,29,Male,IT,Associate,63461,10.3,2020-03-12,4,Young,6161.262136,2020
357,EMP2357,Employee_357,53,Male,HR,Associate,40435,9.6,2021-02-10,4,Senior,4211.979167,2021
377,EMP2377,Employee_377,48,Female,Operations,Executive,21814,15.0,2017-08-23,4,Senior,1454.266667,2017
379,EMP2379,Employee_379,22,Female,Operations,Associate,70258,12.2,2021-01-23,5,Young,5758.852459,2021
386,EMP2386,Employee_386,46,Male,Marketing,Analyst,66806,9.8,2021-11-19,5,Senior,6816.938776,2021
389,EMP2389,Employee_389,38,Female,IT,Associate,55739,11.3,2016-01-04,5,Mid,4932.654867,2016
391,EMP2391,Employee_391,53,Male,HR,Associate,51980,19.9,2017-03-26,4,Senior,2612.060302,2017
400,EMP2400,Employee_400,45,Male,HR,Manager,48141,9.3,2020-11-14,5,Mid,5176.451613,2020
404,EMP2404,Employee_404,25,Male,Marketing,Analyst,26782,9.3,2019-03-04,4,Young,2879.784946,2019
409,EMP2409,Employee_409,33,Male,IT,Lead,28307,13.8,2015-06-15,5,Mid,2051.231884,2015
429,EMP2429,Employee_429,27,Male,IT,Manager,65865,19.4,2015-04-26,5,Young,3395.103093,2015
441,EMP2441,Employee_441,39,Male,Finance,Executive,21881,15.7,2016-11-12,5,Mid,1393.694268,2016
452,EMP2452,Employee_452,54,Male,Marketing,Manager,52443,14.9,2020-07-20,5,Senior,3519.664430,2020
453,EMP2453,Employee_453,48,Female,IT,Associate,62316,12.4,2022-09-22,4,Senior,5025.483871,2022
466,EMP2466,Employee_466,46,Male,IT,Analyst,51422,9.5,2023-03-17,4,Senior,5412.842105,2023
469,EMP2469,Employee_469,42,Female,Finance,Executive,32205,11.6,2020-02-02,4,Mid,2776.293103,2020
477,EMP2477,Employee_477,49,Female,Marketing,Manager,85552,9.0,2023-03-09,5,Senior,9505.777778,2023
479,EMP2479,Employee_479,39,Male,Marketing,Lead,81692,8.5,2019-09-15,4,Mid,9610.823529,2019
485,EMP2485,Employee_485,58,Female,Operations,Lead,58724,18.8,2016-03-31,5,Senior,3123.617021,2016

In [29]:
#4. Average experience > company average
company=df["Experience_Years"].mean()

dept=df.groupby("Department")["Experience_Years"].mean()

dept[dept>company]

Department
Finance      10.244954
HR           10.235106
Marketing    10.340244
Name: Experience_Years, dtype: float64

In [30]:
#5. Correlation
df[["Age","Salary",
"Experience_Years",
"Performance_Rating"]].corr()

                         Age    Salary  Experience_Years  Performance_Rating
Age                 1.000000 -0.007725         -0.017677           -0.008675
Salary             -0.007725  1.000000         -0.013356            0.019948
Experience_Years   -0.017677 -0.013356          1.000000           -0.109150
Performance_Rating -0.008675  0.019948         -0.109150            1.000000

In [31]:
#6. High Risk Attrition
median=df["Salary"].median()

df[(df["Age"]<30)&
   (df["Salary"]<median)&
   (df["Performance_Rating"]<=2)]

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group,Salary_Ratio,Year
2,EMP2002,Employee_2,26,Female,Operations,Executive,30703,15.3,2022-09-05,2,Young,2006.732026,2022
29,EMP2029,Employee_29,25,Female,IT,Analyst,40354,17.6,2023-03-17,2,Young,2292.840909,2023
30,EMP2030,Employee_30,28,Male,Finance,Lead,43929,15.9,2016-03-15,1,Young,2762.830189,2016
42,EMP2042,Employee_42,22,Female,IT,Lead,71493,10.3,2020-01-02,2,Young,6941.067961,2020
52,EMP2052,Employee_52,27,Female,Operations,Lead,51508,9.2,2016-06-07,2,Young,5598.695652,2016
55,EMP2055,Employee_55,29,Male,Operations,Executive,80281,10.3,2016-04-21,2,Young,7794.271845,2016
81,EMP2081,Employee_81,22,Female,IT,Manager,23783,15.4,2022-02-24,1,Young,1544.350649,2022
113,EMP2113,Employee_113,23,Male,Marketing,Associate,30956,16.2,2021-01-23,1,Young,1910.864198,2021
222,EMP2222,Employee_222,26,Male,Finance,Executive,35086,6.3,2022-02-09,1,Young,5569.206349,2022
234,EMP2234,Employee_234,25,Male,Finance,Lead,30283,2.0,2018-02-20,2,Young,15141.500000,2018
253,EMP2253,Employee_253,26,Male,HR,Lead,59791,11.2,2017-02-23,1,Young,5338.482143,2017
293,EMP2293,Employee_293,29,Male,Operations,Executive,73218,7.6,2019-06-22,1,Young,9633.947368,2019
302,EMP2302,Employee_302,26,Female,Finance,Executive,36806,3.9,2020-01-01,1,Young,9437.435897,2020
310,EMP2310,Employee_310,24,Female,Marketing,Lead,30589,9.7,2022-05-20,2,Young,3153.505155,2022
328,EMP2328,Employee_328,22,Male,Operations,Lead,24552,19.9,2016-06-18,2,Young,1233.768844,2016
339,EMP2339,Employee_339,22,Male,Finance,Associate,23722,7.4,2021-07-19,2,Young,3205.675676,2021
367,EMP2367,Employee_367,23,Male,Operations,Analyst,76635,16.5,2019-03-09,1,Young,4644.545455,2019
407,EMP2407,Employee_407,29,Female,IT,Analyst,45933,16.0,2016-10-08,2,Young,2870.812500,2016

In [32]:
#7. Department Salary Rank
df["Salary_Rank"]=df.groupby("Department")["Salary"].rank(ascending=False)

df

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Experience_Years,Joining_Date,Performance_Rating,Age_Group,Salary_Ratio,Year,Salary_Rank
0,EMP2000,Employee_0,42,Male,Marketing,Executive,144857,13.4,2019-06-11,1,Mid,10810.223881,2019,3.0
1,EMP2001,Employee_1,42,Female,IT,Manager,39738,17.5,2015-10-14,5,Mid,2270.742857,2015,100.0
2,EMP2002,Employee_2,26,Female,Operations,Executive,30703,15.3,2022-09-05,2,Young,2006.732026,2022,84.0
3,EMP2003,Employee_3,41,Male,Operations,Executive,133776,14.7,2018-05-20,5,Mid,9100.408163,2018,10.0
4,EMP2004,Employee_4,58,Female,HR,Executive,69422,9.9,2019-03-28,5,Senior,7012.323232,2019,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,EMP2495,Employee_495,43,Female,Finance,Manager,143805,9.7,2023-02-06,1,Mid,14825.257732,2023,6.0
496,EMP2496,Employee_496,54,Female,Marketing,Executive,113846,1.3,2019-10-03,4,Senior,87573.846154,2019,28.0
497,EMP2497,Employee_497,57,Female,Finance,Executive,42927,14.1,2022-08-21,1,Senior,3044.468085,2022,86.0
498,EMP2498,Employee_498,44,Male,Marketing,Associate,140589,6.9,2020-05-25,4,Mid,20375.217391,2020,7.0
499,EMP2499,Employee_499,55,Male,Marketing,Executive,135657,15.0,2020-12-12,1,Senior,9043.800000,2020,10.0